## This file was automatically generated by configGen.py version 1.1 from 10/27/17

## This code was developed and authored by Les Klimczak, Ph.D. 
## Unauthorized commercial reuse of the code and removal of this notice
## are prohibited.
## This research was supported by the Intramural Research Program of the NIH,
## National Institute of Environmental Health Sciences.

## EDIT START 1 ##

#CUSTOMTYPE <- "aTy"
CUSTOMTYPE <- "aTy"
ANALYZECOLS <- c("aTy", "rAt")
# introduced with the UV pipeline
CUSTOMMUTLOAD <- TRUE
# MUTFIELDNAME should agree with custFields No.2
# current naming style to consolidate older versions wCy_to_T+rGw_to_A, wCy_to_T
MUTFIELDNAME <- "aTy_to_C+revcomp"
# "[aTy_to_C+revcomp]_per_mut"
perMutFieldName <- paste("[", MUTFIELDNAME, "]_per_mut", sep="")

# Motif definitions:

# for findMotifs.R
# Rule: derive from the findTitles list by expanding IUPAC Codes with their bases
motifs2Find <- c("A", "T", "G", "C", "aT[ct]", "[ag]At")
findTitles <- c("A", "T", "G", "C", "aTy", "rAt")

# for countMotifs.R
# Rule: derive from the countTitles list by expanding IUPAC Codes with their bases
motifs2Count <- c("a", "t", "g", "c", "at[ct]", "[ag]at")
countTitles <- c("a", "t", "g", "c", "aty", "rat")

# for analyzeAutoExt.R

# Analysis module formulas:

getCustomFields <- function() {
         custFields <- c(
# [aTy_to_C+rAt_to_G]_per_mut
(aTy_to_C + rAt_to_G) / mutations, 
# aTy_to_C+rAt_to_G
aTy_to_C+rAt_to_G, 
# Rule: C_to_T derive from wCy_to_T by removing lowercase bases
# Rule: G_to_A derive from rGw_to_A by removing lowercase bases
# [T_to_C-aTy_to_C]
(T_to_C + A_to_G) - (aTy_to_C + rAt_to_G), 
# aty+rat, 
aty+rat, 
# Rule: c derive from wCy by taking the capitalized mutated base in lowercase
# Rule: g derive from rGw by taking the capitalized mutated base in lowercase
# t-aty 
(t + a) - (aty+rat)
         )

# Rule: C_to_T derive from wCy_to_T by leaving only the capitalized mutated base in the motif
# Rule: G_to_A derive from rGw_to_A by leaving only the capitalized mutated base in the motif 
         testMat <- rbind(c((aTy_to_C + rAt_to_G), (T_to_C + A_to_G - aTy_to_C - rAt_to_G )),c(aty+rat, t+a-aty-rat))
         ft <- fisher.test(testMat, alternative="greater")

 testFields <- c(
# Fisher_p-value_wCy
ft$p.value,
# odds_ratio_wCy
ft$estimate,
#paste(ft$conf.int, collapse="-")
# 95%_confidence_lower_wCy
ft$conf.int[1],
# 95%_confidence_upper_wCy
ft$conf.int[2]
         )

         custFields2 <- c(
# aTy_enrich
((aTy_to_C+rAt_to_G) * (t+a))/((T_to_C + A_to_G) * (aty+rat)))

                                					
## EDIT END 1 ##

	#newFields <- c(custFields,testFields,custFields2,testFields2)
	newFields <- c(custFields,testFields,custFields2)
	return(newFields)
}

# all the column names that appear in the above formulas as comments should be grouped here
# this will replace the fisherSample file
newFieldTitles <- c(
perMutFieldName,
MUTFIELDNAME,
## EDIT START 3 ##
"[T_to_C-aTy_to_C]+revcomp",
"aty+revcomp",
"t-aty+revcomp",
## EDIT END 3 ##
paste("Fisher_p-value_", CUSTOMTYPE, sep=""),
paste("odds_ratio_", CUSTOMTYPE, sep=""),
paste("95%_confidence_lower_", CUSTOMTYPE, sep=""),
paste("95%_confidence_upper_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

# for addSampleCols.R

sampleTitles <- c(
perMutFieldName,
MUTFIELDNAME,
paste("BH_Fisher_p-value_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

if (CUSTOMMUTLOAD) {
sampleTitles <- c(sampleTitles,
# aTy_MutLoad_MinEstimate
paste(CUSTOMTYPE, "_MutLoad_MinEstimate", sep="")
)
}



