## This file was automatically generated by configGen2.py version  2.3.1 from 02/14/22

## This code was developed and authored by Les Klimczak, Ph.D. 
## Unauthorized commercial reuse of the code and removal of this notice
## are prohibited.
## This research was supported by the Intramural Research Program of the NIH,
## National Institute of Environmental Health Sciences.

## EDIT START 1 ##

#CUSTOMTYPE <- "aTr"
CUSTOMTYPE <- "aTr"
ANALYZECOLS <- c("aTr", "yAt")
# introduced with the UV pipeline
CUSTOMMUTLOAD <- TRUE
# MUTFIELDNAME should agree with custFields No.2
# current naming style to consolidate older versions wCy_to_T+rGw_to_A, wCy_to_T
MUTFIELDNAME <- "aTr_to_C+revcomp"
# "[aTr_to_C+revcomp]_per_mut"
perMutFieldName <- paste("[", MUTFIELDNAME, "]_per_mut", sep="")

# Motif definitions:

# for findMotifs.R
# Rule: derive from the findTitles list by expanding IUPAC Codes with their bases
motifs2Find <- c("A", "T", "G", "C", "aT[ag]", "[ct]At")
findTitles <- c("A", "T", "G", "C", "aTr", "yAt")

# for countMotifs.R
# Rule: derive from the countTitles list by expanding IUPAC Codes with their bases
motifs2Count <- c("a", "t", "g", "c", "at[ag]", "[ct]at")
countTitles <- c("a", "t", "g", "c", "atr", "yat")

# for analyzeAutoExt.R

# Analysis module formulas:

getCustomFields <- function() {
         custFields <- c(
# [aTr_to_C+yAt_to_G]_per_mut
(aTr_to_C + yAt_to_G) / mutations, 
# aTr_to_C+yAt_to_G
aTr_to_C+yAt_to_G, 
# Rule: C_to_T derive from wCy_to_T by removing lowercase bases
# Rule: G_to_A derive from rGw_to_A by removing lowercase bases
# [T_to_C-aTr_to_C]
(T_to_C + A_to_G) - (aTr_to_C + yAt_to_G), 
# atr+yat, 
atr+yat, 
# Rule: c derive from wCy by taking the capitalized mutated base in lowercase
# Rule: g derive from rGw by taking the capitalized mutated base in lowercase
# t-atr 
(t + a) - (atr+yat)
         )

# Rule: C_to_T derive from wCy_to_T by leaving only the capitalized mutated base in the motif
# Rule: G_to_A derive from rGw_to_A by leaving only the capitalized mutated base in the motif 
         testMat <- rbind(c((aTr_to_C + yAt_to_G), (T_to_C + A_to_G - aTr_to_C - yAt_to_G )),c(atr+yat, t+a-atr-yat))
         ft <- fisher.test(testMat, alternative="greater")

 testFields <- c(
# Fisher_p-value_wCy
ft$p.value,
# odds_ratio_wCy
ft$estimate,
#paste(ft$conf.int, collapse="-")
# 95%_confidence_lower_wCy
ft$conf.int[1],
# 95%_confidence_upper_wCy
ft$conf.int[2]
         )

         custFields2 <- c(
# aTr_enrich
((aTr_to_C+yAt_to_G) * (t+a))/((T_to_C + A_to_G) * (atr+yat)))

                                					
## EDIT END 1 ##

	#newFields <- c(custFields,testFields,custFields2,testFields2)
	newFields <- c(custFields,testFields,custFields2)
	return(newFields)
}

# all the column names that appear in the above formulas as comments should be grouped here
# this will replace the fisherSample file
newFieldTitles <- c(
perMutFieldName,
MUTFIELDNAME,
## EDIT START 3 ##
"[T_to_C-aTr_to_C]+revcomp",
"atr+revcomp",
"t-atr+revcomp",
## EDIT END 3 ##
paste("Fisher_p-value_", CUSTOMTYPE, sep=""),
paste("odds_ratio_", CUSTOMTYPE, sep=""),
paste("95%_confidence_lower_", CUSTOMTYPE, sep=""),
paste("95%_confidence_upper_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

# for addSampleCols.R

sampleTitles <- c(
perMutFieldName,
MUTFIELDNAME,
paste("BH_Fisher_p-value_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

if (CUSTOMMUTLOAD) {
sampleTitles <- c(sampleTitles,
# aTr_MutLoad_MinEstimate
paste(CUSTOMTYPE, "_MutLoad_MinEstimate", sep="")
)
}



