## This file was automatically generated by configGen.py version 2.3 from 03/16/21

## This code was developed and authored by Les Klimczak, Ph.D. 
## Unauthorized commercial reuse of the code and removal of this notice
## are prohibited.
## This research was supported by the Intramural Research Program of the NIH,
## National Institute of Environmental Health Sciences.

## EDIT START 1 ##

#CUSTOMTYPE <- "aTn"
CUSTOMTYPE <- "aTn"
ANALYZECOLS <- c("aTn", "nAt")
# introduced with the UV pipeline
CUSTOMMUTLOAD <- TRUE
# MUTFIELDNAME should agree with custFields No.2
# current naming style to consolidate older versions wCy_to_T+rGw_to_A, wCy_to_T
MUTFIELDNAME <- "aTn_to_C+revcomp"
# "[aTn_to_C+revcomp]_per_mut"
perMutFieldName <- paste("[", MUTFIELDNAME, "]_per_mut", sep="")

# Motif definitions:

# for findMotifs.R
# Rule: derive from the findTitles list by expanding IUPAC Codes with their bases
motifs2Find <- c("A", "T", "G", "C", "aT[acgt]", "[acgt]At")
findTitles <- c("A", "T", "G", "C", "aTn", "nAt")

# for countMotifs.R
# Rule: derive from the countTitles list by expanding IUPAC Codes with their bases
motifs2Count <- c("a", "t", "g", "c", "at[acgt]", "[acgt]at")
countTitles <- c("a", "t", "g", "c", "atn", "nat")

# for analyzeAutoExt.R

# Analysis module formulas:

getCustomFields <- function() {
         custFields <- c(
# [aTn_to_C+nAt_to_G]_per_mut
(aTn_to_C + nAt_to_G) / mutations, 
# aTn_to_C+nAt_to_G
aTn_to_C+nAt_to_G, 
# Rule: C_to_T derive from wCy_to_T by removing lowercase bases
# Rule: G_to_A derive from rGw_to_A by removing lowercase bases
# [T_to_C-aTn_to_C]
(T_to_C + A_to_G) - (aTn_to_C + nAt_to_G), 
# atn+nat, 
atn+nat, 
# Rule: c derive from wCy by taking the capitalized mutated base in lowercase
# Rule: g derive from rGw by taking the capitalized mutated base in lowercase
# t-atn 
(t + a) - (atn+nat)
         )

# Rule: C_to_T derive from wCy_to_T by leaving only the capitalized mutated base in the motif
# Rule: G_to_A derive from rGw_to_A by leaving only the capitalized mutated base in the motif 
         testMat <- rbind(c((aTn_to_C + nAt_to_G), (T_to_C + A_to_G - aTn_to_C - nAt_to_G )),c(atn+nat, t+a-atn-nat))
         ft <- fisher.test(testMat, alternative="greater")

 testFields <- c(
# Fisher_p-value_wCy
ft$p.value,
# odds_ratio_wCy
ft$estimate,
#paste(ft$conf.int, collapse="-")
# 95%_confidence_lower_wCy
ft$conf.int[1],
# 95%_confidence_upper_wCy
ft$conf.int[2]
         )

         custFields2 <- c(
# aTn_enrich
((aTn_to_C+nAt_to_G) * (t+a))/((T_to_C + A_to_G) * (atn+nat)))

                                					
## EDIT END 1 ##

	#newFields <- c(custFields,testFields,custFields2,testFields2)
	newFields <- c(custFields,testFields,custFields2)
	return(newFields)
}

# all the column names that appear in the above formulas as comments should be grouped here
# this will replace the fisherSample file
newFieldTitles <- c(
perMutFieldName,
MUTFIELDNAME,
## EDIT START 3 ##
"[T_to_C-aTn_to_C]+revcomp",
"atn+revcomp",
"t-atn+revcomp",
## EDIT END 3 ##
paste("Fisher_p-value_", CUSTOMTYPE, sep=""),
paste("odds_ratio_", CUSTOMTYPE, sep=""),
paste("95%_confidence_lower_", CUSTOMTYPE, sep=""),
paste("95%_confidence_upper_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

# for addSampleCols.R

sampleTitles <- c(
perMutFieldName,
MUTFIELDNAME,
paste("BH_Fisher_p-value_", CUSTOMTYPE, sep=""),
paste(CUSTOMTYPE, "_enrich", sep="")
)

if (CUSTOMMUTLOAD) {
sampleTitles <- c(sampleTitles,
# aTn_MutLoad_MinEstimate
paste(CUSTOMTYPE, "_MutLoad_MinEstimate", sep="")
)
}



